# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Require colors..
require './color'

# Lets get this party started
if !ARGV.include?("halt") && !ARGV.include?("destroy")
    puts "Welcome, developer! 😎".green
    puts "Human contact possible @ https://github.com/orgs/UKMNorge/teams/developers".green
end

# Global vars
$localNFSpath = "#{Dir.pwd}/"
$boxNames = []

# Files we kinda need
require './filesystem'      # File system functions
require './dependencies'    # Vagrant plugin dependencies
require './boxconfig'       # Different vagrant-box configs
require './utils'           # VM conf utilities

# Configure vagrant!
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "ubuntu/bionic64"
  
    # Share the salt config with the guest
    config.vm.synced_folder "salt", "/srv/salt/"
    config.vm.synced_folder "pillar", "/srv/pillar"

    # Setup host manager
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.include_offline = true   # So every box knows each other, even if currently offline

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", $boxConf['main'][:memory]]
    end

    ## main MAIN SERVER (UKM.no)
    config.vm.define "main", primary: true do |main|
        # Box basic config
        commonConf('main', main)
        # Share wordpress folders
        share(main, 'main/plugins', '/var/www/wordpress/wp-content/plugins/')
        share(main, 'main/themes', '/var/www/wordpress/wp-content/themes/')
        # Share UKMlib folder
        share(main, 'main/ukmlib', '/etc/php-includes/UKM/')
        # Share folders and setup hosts file for subdomains
        shareAndConfigureSubdomains('main', main, config);
        # Provision (salt-stack)
        doProvision('main',main)
    end

    ## LITE main SERVER (for project fun)
    config.vm.define "lite" do |lite|
        #  Box basic config
        commonConf('lite', lite)
        # Share web and UKMlib folder
        share(lite, 'lite/www', '/var/www/lite/')        
        share(lite, 'lite/ukmlib', '/etc/php-includes/UKM/')
        # Share folders and setup hosts file for subdomains
        shareAndConfigureSubdomains('lite', lite, config);
        
        ##############################################
        # Temp workaround
        # https://github.com/UKMNorge/servere/issues/2
        lite.hostmanager.aliases << 'ukm.dev'
        ##############################################

        # Provision (salt-stack)
        doProvision('lite',lite)
    end

    ## playback Mediefiler-server (playback.ukm.no)
    config.vm.define "playback" do |playback|
        commonConf('playback', playback)
        share(playback, 'playback/www', '/var/www/playback/')
        shareAndConfigureSubdomains('playback', playback, config)
        doProvision('playback', playback)
    end

    config.vm.define "videoconverter" do |videoconverter|
        commonConf('videoconverter', videoconverter)
        #share(videoconverter, 'videoconverter', '/var/www/videoconverter')
        shareAndConfigureSubdomains('videoconverter', videoconverter, config)
        doProvision('videoconverter', videoconverter)
    end
end